package prova320172;

import java.io.IOException;

public class Main {

	public static void main(String[] args) throws IOException{
		
		SiRePro sirepro = new SiRePro();
		
		sirepro.cadastrarPessoa("Eduardo", 1, 1, 1);
		sirepro.cadastrarPessoa("Leidiane", 1, 1, 1);
		sirepro.cadastrarPessoa("Hosaneide", 1, 1, 1);
		sirepro.cadastrarPessoa("Edvaldo", 1, 1, 1);
		sirepro.cadastrarPessoa("Aercio", 1, 1, 1);
		sirepro.cadastrarPessoa("Fabio", 1, 1, 1);
		sirepro.cadastrarPessoa("Ladjane", 1, 1, 1);
		sirepro.cadastrarPessoa("Neide", 1, 1, 1);
		sirepro.cadastrarPessoa("ggg", 1, 1, 1);


	}

}
